name: trade_flatform
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  media_info: ^0.10.0
  path_provider: ^2.0.10
  video_thumbnail: ^0.5.0
  flutter_easyloading: ^3.0.5
  provider: ^6.0.3
  carousel_slider: ^4.1.1
  model_viewer_plus: ^1.2.0
  google_fonts: ^3.0.1
  select_form_field: "^2.2.0"
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  image_picker: ^0.8.5+3

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/images/
